image: Ubuntu1804
configuration: Release
platform: Any CPU
version: '1.0.{build}'
skip_tags: true
install:
  - sh: sudo apt-get update
  - sh: sudo apt-get install -y git clang cmake make gcc g++ libssl-dev libbz2-dev libreadline-dev libncurses-dev libboost-all-dev p7zip
  - sh: sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
  - sh: sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang 100