image: Ubuntu1804
platform: Any CPU

version: '1.0.{build}'
skip_tags: true

install:
  - sh: sudo apt-get update
  - sh: sudo apt-get install -y mysql-server mysql-client libmysqlclient-dev libmysql++-dev git clang cmake make gcc g++ libssl-dev libbz2-dev libreadline-dev libncurses-dev libboost-all-dev p7zip
  - sh: sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
  - sh: sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang 100
  
before_build:
  - sh: mkdir build
  - sh: cd build
  - sh: cmake ../ -DCMAKE_INSTALL_PREFIX=/home/root/bin

build:
  verbosity: normal
  
artifacts:
  path: /home/appveyor/projects/elunatrinitywotlk/build
  name: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_BUILD_VERSION)
  type: zip